//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.17 at 08:38:02 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.collada.org/2005/11/COLLADASchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.collada.colladaschema;
